### ISSUE TITLE
USER STORY: Account Registration (User)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/project-5-frontend#1]
As a **user**, I can **create an account** so that **I can create and contribute to projects**.

---
#### Acceptance Criteria
**1.** Account details are authenticated during registration
**2.** User can register, log in and out of account using links in navbar
**3.** Certain content cannot be viewed/interacted with unless logged in

---
#### Tasks
- [x] Install and implement dj-rest-auth and link to sign-up form
- [x] Style registration and login forms
- [x] Add dynamic login/out links to navigation
- [x] Add authentication requirements for certain actions and content
