### ISSUE TITLE
USER STORY: Customise Profile (User)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/project-5-frontend#11]
As a **user**, I can **customise my profile** so that **other users can identify me easily**.

---
#### Acceptance Criteria
**1.** User is able to add their first name, last name and a short bio
**2.** Prompted at registration

---
#### Tasks
- [x] Add "Edit Profile" form
- [x] Display user's when inviting as contributor
- [x] Add avatar to display public profile info on hover
