### ISSUE TITLE
USER STORY: Manage Contents (Admin)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/project-5-frontend#2]
As an **admin**, I can **edit and remove projects, tasks and comments** so that **I can manage the site contents**.

---
#### Acceptance Criteria
**1.** Contents can be viewed, edited and removed via the admin panel
**2.** 404 page displays when trying to access removed content
**3.** User is alerted when their content is removed/edited, with 'reason' displayed

---
#### Tasks
- [x] Create at least 1 custom model
- [x] Create superuser to access admin panel
- [x] Add search box and filter to admin panel
- [x] Redirect to 404 if trying to access removed content
