### ISSUE TITLE
USER STORY: Create Project (User)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/project-5-frontend#3]
As a **user**, I can **create my own project(s)** so that **I can plan and track their progress**.

---
#### Acceptance Criteria
**1.** User must be logged in to create and contribute to a Project
**2.** User can create/contribute to multiple projects
**3.** Projects are displayed in an account menu only to those with permission

---
#### Tasks
- [x] Build "Project" model
- [x] Create "New Project" form
- [x] Add authentication
- [x] Display user's projects in navigation
