### ISSUE TITLE
USER STORY: Control Project Privacy (User)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/project-5-frontend#7]
As a **project owner**, I can **set the projects visibility to others** so that **I can decide who views it**.

---
#### Acceptance Criteria
**1.** Owner can set the project visibility to everyone or contributors only
**2.** Projects that are visible to all are only editable to contributors
**3.** 

---
#### Tasks
- [ ] Add visibility field to model
- [ ] Add toggle to Add/Edit form
- [ ] Hide Add/Edit buttons from non-contributors
